### PR TITLE
fix velocity changed shows Save button

### LINKED ISSUE #258: Changing Velocity does not show Save button
> when I switch between “Deliver Fast” and “Deliver Evenly” it doesn’t give me the option to Save. I have to make an additional change in order to be able to save.

### PR DESCRIPTION
**Pull request by sandikbarr**
closes #258 
Implements velocity as a FormControl: 
  * Coming in from the API, velocity is set on the flight model from totalGoal and dailyMin
  * Changes to velocity set the dailyMin, which emits an update because this change is persisted
  * Changes to dailyMinimum or totalGoal set the velocity, which does not emit an update because velocity is not persisted and is just UI state

### CODE REVIEW

File: src/app/campaign/inventory/goal-form.component.ts [hunk 1]
```diff
@@ -98,24 +103,29 @@ export class GoalFormComponent implements OnInit {
 
   ngOnInit() {
     this.goalForm = this.formController.control as FormGroup;
+    this.velocitySub = this.goalForm.get('velocity').valueChanges.subscribe(velocity => this.setDailyMinimum(velocity));
+    this.goalMinSub = combineLatest([this.goalForm.get('totalGoal').valueChanges, this.goalForm.get('dailyMinimum').valueChanges])
```
Comment (sandikbarr) [inline src/app/campaign/inventory/goal-form.component.ts]: once totalGoal and dailyMinimum have been set, the velocity will be set accordingly

File: src/app/campaign/inventory/goal-form.component.ts [hunk 2]
```diff
@@ -98,24 +103,29 @@ export class GoalFormComponent implements OnInit {
...
+  ngOnDestroy() {
+    if (this.velocitySub) {
+      this.velocitySub.unsubscribe();
     }
+    if (this.goalMinSub) {
+      this.goalMinSub.unsubscribe();
+    }
+  }
+
+  setVelocity(totalGoal: number, dailyMinimum: number) {
```
Comment (sandikbarr) [inline src/app/campaign/inventory/goal-form.component.ts:128]: don't emit velocity changes set from the totalGoal and dailyMin. a) prevents circular update cycle b) velocity is really just UI state, so it doesn't need to push those updates out anywhere else

File: src/app/campaign/store/actions/campaign-action.service.spec.ts [hunk 3]
```diff
@@ -120,14 +120,12 @@ describe('CampaignActionService', () => {
...
       const yesterday = moment.utc(today.valueOf()).subtract(1, 'days');
       service.updateFlightForm({ ...flightFixture, endAtFudged: yesterday, contractEndAtFudged: yesterday }, true, true);
-      expect(JSON.stringify(dispatchSpy.mock.calls[dispatchSpy.mock.calls.length - 1][0])).toEqual(
-        JSON.stringify(
-          campaignActions.CampaignFlightFormUpdate({
-            flight: { ...flightFixture, endAt: today, endAtFudged: yesterday, contractEndAtFudged: yesterday, contractEndAt: today },
-            changed: true,
-            valid: true
-          })
-        )
```
Comment (sandikbarr) [inline src/app/campaign/store/actions/campaign-action.service.spec.ts:130]: Seems like a separate issue, but trying to address that tests are hanging on
```
(node:85206) UnhandledPromiseRejectionWarning: TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property 'element' -> object with constructor 'Object'
    |     property 'publicProviders' -> object with constructor 'Object'
    |     property 'ɵNgNoValidate_122' -> object with constructor 'Object'
    --- property 'parent' closes the circle
    at JSON.stringify (<anonymous>)
    at process.target._send (internal/child_process.js:778:25)
    at process.target.send (internal/child_process.js:676:19)
    at reportSuccess (/Users/sandikbarr/code/grove.prx.org/node_modules/jest-worker/build/workers/processChild.js:67:11)
(node:85206) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:85206) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

File: src/app/dashboard/dashboard.service.mock.ts [hunk 4]
```diff
@@ -75,15 +73,12 @@ export const campaigns: Campaign[] = [
...
     notes: '',
-    flights,
     loading: false,
     actualCount: 125000,
     totalGoal: 100000
   }
 ];
 
-flights.forEach(flight => (flight.parent = campaigns[0]));
-
```
Comment (sandikbarr) [inline src/app/dashboard/dashboard.service.mock.ts:86]: Another change to try to address that tests are hanging on. Did not fix the problem.
```
(node:85206) UnhandledPromiseRejectionWarning: TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property 'element' -> object with constructor 'Object'
    |     property 'publicProviders' -> object with constructor 'Object'
    |     property 'ɵNgNoValidate_122' -> object with constructor 'Object'
    --- property 'parent' closes the circle
    at JSON.stringify (<anonymous>)
    at process.target._send (internal/child_process.js:778:25)
    at process.target.send (internal/child_process.js:676:19)
    at reportSuccess (/Users/sandikbarr/code/grove.prx.org/node_modules/jest-worker/build/workers/processChild.js:67:11)
(node:85206) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:85206) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

File: src/app/campaign/store/actions/campaign-action.service.spec.ts (hunk 3 above)
Comment (sandikbarr) [reply src/app/campaign/store/actions/campaign-action.service.spec.ts:130]: Gah, disregard. The tests hanging and this UnhandledPromiseRejectionWarning error were actually errors happening in the tests from velocity not being included in the spec's form group. When I ran those tests individually, the errors were reported, but this is what I saw when I ran the whole test suite.

File: src/app/dashboard/dashboard.service.mock.ts (hunk 4 above)
Comment (sandikbarr) [reply src/app/dashboard/dashboard.service.mock.ts:86]: Cool, cool. This was not the problem. Still probably a valid change though in general, so keeping it.

**Review by cavis — APPROVED** [review]
Slight tweak to always allow selecting "deliver fast", and trigger the valuechanges even if only 1 of totalGoal/dailyMin has changed.  But otherwise +1 all works!
